permalink: /blog/:title

# My variables
name: Sukun Tarachandani	
description: mostly harmless
google_verification: null

include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

sass:
  style: :compressed
  sass_dir: _sass

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
