baseURL: https://sukunrt.github.io
languageCode: en-us
title: Sukun Tarachandani
theme: vanilla-bootstrap-hugo-theme

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

# See https://feathericons.com/
# The value of pre is the icon name
menu:
  nav:
  - name: Home
    pre: home
    url: /
    weight: 1
  - name: Blog
    pre: edit
    url: /post/
    weight: 2
  - name: Tags
    pre: tag
    url: /tags/
    weight: 3
  - name: RSS
    pre: rss
    url: /index.xml
    weight: 5

params:
  includeBootstrapJs: false
  showActiveNav: true
  containerMaxWidth: 700px
  dateFormat: Jan 2, 2006
  homeText: Hi, I'm a software engineer interested in p2p and decentralised systems. 
  footerText: Made with [Hugo](https://gohugo.io/) & [Vanilla](https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme)
  hideFooter: false
  katex: true


pygmentsUseClasses: true

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: false
    style: friendly
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
